version: '3'

services:
  seed:
    build:
      context: "."
      dockerfile: cassandra_node.dockerfile
    hostname: seed
    environment:
      - CASSANDRA_CLUSTER_NAME=xandra-cluster
      - CASSANDRA_DC=xandradc
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
      - START_RPC=false
      - NUM_TOKENS=3
      - RACK=RAC1
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000

  node1:
    build:
      context: "."
      dockerfile: cassandra_node.dockerfile
    hostname: node1
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_CLUSTER_NAME=xandra-cluster
      - CASSANDRA_DC=xandradc
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    depends_on:
      - seed

  node2:
    build:
      context: "."
      dockerfile: cassandra_node.dockerfile
    hostname: node2
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_CLUSTER_NAME=xandra-cluster
      - CASSANDRA_DC=xandradc
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    depends_on:
      - seed

  node3:
    build:
      context: "."
      dockerfile: cassandra_node.dockerfile
    hostname: node3
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_CLUSTER_NAME=xandra-cluster
      - CASSANDRA_DC=xandradc
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    depends_on:
      - seed

  elixir:
    # We need to build from the root of Xandra itself so that we can copy Xandra's code inside
    # the container, but then we want to use the Dockerfile in this directory.
    build:
      context: ".."
      dockerfile: ./test_clustering/Dockerfile
    links:
      - seed
      - node1
      - node2
      - node3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CASSANDRA_NATIVE_PROTOCOL
