version: '3'

services:
  cassandra:
    build:
      context: ./test/docker
      dockerfile: cassandra.dockerfile
      args:
        CASSANDRA_VERSION: "${CASSANDRA_VERSION:-4.1}"
    ports:
      - "9052:9042" # TCP connections
      - "9152:9142" # TLS/SSL connections
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  cassandra_with_auth:
    build:
      context: ./test/docker
      dockerfile: cassandra.dockerfile
      args:
        AUTHENTICATION: "true"
        CASSANDRA_VERSION: "${CASSANDRA_VERSION:-4.1}"
    ports:
      - "9053:9042"
    environment:
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=200M
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  scylladb:
    build:
      context: ./test/docker
      dockerfile: scylladb.dockerfile
      args:
        SCYLLA_VERSION: ${SCYLLA_VERSION:-5.1.6}
    ports:
      - "9062:9042"
      - "10000:10000"
    command:
      - "--smp"
      - "1"
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  scylladb_with_auth:
    build:
      context: ./test/docker
      dockerfile: scylladb.dockerfile
      args:
        SCYLLA_VERSION: ${SCYLLA_VERSION:-5.1.6}
        AUTHENTICATION: "true"
    ports:
      - "9063:9042"
    command:
      - "--smp"
      - "1"
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    ports:
      - "8474:8474"
      - "19052:19052"
    environment:
      LOG_LEVEL: trace
    healthcheck:
      test: [ "CMD-shell", "exit 0" ]
      interval: 2s
      timeout: 4s
      retries: 5
