version: '3'

services:
  scylladb:
    build:
      context: ./test/docker
      dockerfile: scylladb.dockerfile
      args:
        SCYLLA_VERSION: ${SCYLLA_VERSION:-4.6.2}
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  scylladb_with_auth:
    build:
      context: ./test/docker
      dockerfile: scylladb.dockerfile
      args:
        SCYLLA_VERSION: ${SCYLLA_VERSION:-4.6.2}
        AUTHENTICATION: "true"
    ports:
      - "9043:9042"
    healthcheck:
      test: [ "CMD-SHELL", "nodetool -h ::FFFF:127.0.0.1 status" ]
      interval: 20s
      timeout: 10s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: 50m
