name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: >
      Test (Elixir ${{ matrix.elixir }},
      OTP ${{ matrix.otp }},
      C* ${{ matrix.cassandra_version }},
      Native protocol ${{ matrix.cassandra_native_protocol || 'auto' }})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Without a forced protocol (let Xandra figure it out), newest C*.
          - otp: "24.2"
            elixir: "1.13"
            cassandra_version: "4.0"
            lint: true

          # Without a forced protocol (let Xandra figure it out), older C*.
          - otp: "24.2"
            elixir: "1.13"
            cassandra_version: "3"

          # Native protocol v4 on C* version 3.
          - otp: "24.2"
            elixir: "1.13"
            cassandra_version: "3"
            cassandra_native_protocol: "v4"

          # Force an older protocol: native protocol v3 on newer C* 4.
          - otp: "24.2"
            elixir: "1.13"
            cassandra_version: "4.0"
            cassandra_native_protocol: "v3"

          # Old C* version, 2.2. We don't specify the native protocol
          # because Xandra should not use anything that the server doesn't
          # support anyways.
          - otp: "24.2"
            elixir: "1.13"
            cassandra_version: "2.2"

          # Oldest supported Elixir/OTP matrix.
          # Elixir 1.9 supports OTP 20, but telemetry doesn't, so we force
          # OTP 21 here.
          - otp: "21.3"
            elixir: "1.9"
            cassandra_version: "3"
            cassandra_native_protocol: "v3"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test
      CASSANDRA_VERSION: ${{ matrix.cassandra_version }}
      CASSANDRA_NATIVE_PROTOCOL: ${{ matrix.cassandra_native_protocol }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Start Docker and wait for it to be up
        run: |
          docker-compose up --detach --build
          ./test/docker/health-check-services.sh

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get --only test
          mix deps.compile

      - name: Check formatting
        run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - name: Check no unused dependencies
        run: mix deps.get && mix deps.unlock --check-unused
        if: ${{ matrix.lint == 'true' && steps.cache-deps.outputs.cache-hit != 'true' }}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run tests
        run: mix test --trace

      - name: Run clustering end-to-end tests
        run: mix test.clustering

      - name: Dump Docker logs on failure
        uses: jwalton/gh-docker-logs@v1
        if: failure()

  test_scylla:
    name: >
      Test ScyllaDB (Elixir ${{ matrix.elixir }},
      OTP ${{ matrix.otp }},
      Scylla ${{ matrix.scylla_version }},
      Native protocol ${{ matrix.cassandra_native_protocol || 'auto' }})
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Negotiated native protocol.
          - otp: "24.2"
            elixir: "1.13"
            scylla_version: "4.6.2"

          # Forced native protocol v4.
          - otp: "24.2"
            elixir: "1.13"
            scylla_version: "4.6.2"
            cassandra_native_protocol: "v4"

          # Forced native protocol v3.
          - otp: "24.2"
            elixir: "1.13"
            scylla_version: "4.6.2"
            cassandra_native_protocol: "v3"

    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      MIX_ENV: test
      SCYLLA_VERSION: ${{ matrix.scylla_version }}
      CASSANDRA_NATIVE_PROTOCOL: ${{ matrix.cassandra_native_protocol }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2

      - name: Start Docker and wait for it to be up
        run: |
          docker-compose --file docker-compose.scylladb.yml up --detach
          ./test/docker/health-check-services.sh

      - name: Install OTP and Elixir
        uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-otp${{ matrix.otp }}-elixir${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          mix deps.get --only test
          mix deps.compile

      - name: Run tests
        run: mix test.scylladb

      - name: Dump Docker logs on failure
        uses: jwalton/gh-docker-logs@v1
        if: failure()
